---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Install prometheus
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Copy prometheus file to bin
      copy:
        src: "/tmp/prometheus-2.36.2.linux-amd64/prometheus"
        dest: "/usr/local/bin/prometheus"
        owner: ubuntu
        group: ubuntu
        remote_src: yes
        mode: 0755
    - name: Creates directory
      file: 
        path: "/data/prometheus/"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Creates directory
      file: 
        path: "/etc/prometheus/"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Creates directory
      file:
        path: "/var/lib/prometheus/"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
         
    - name: Copy prometheus config file
      template:
        src: ../templates/prometheus.yml
        dest: /etc/prometheus/prometheus.yml

    - name: Copy prometheus service file
      template:
        src: ../templates/prometheus.service
        dest: /etc/systemd/system/prometheus.service

    - name: reload systemd
      shell: systemctl daemon-reload    

    - name: Start prometheus service
      service:
        name: prometheus
        state: restarted

    - name: Installing grafan
      shell: |
        /bin/wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add - 
        /bin/add-apt-repository "deb https://packages.grafana.com/oss/deb stable main" 
        /bin/apt-get update 
        /bin/apt-get install -y  grafana
      become: true  
    - name: Start Grafana service
      service:
        name: grafana-server
        state: restarted 

